
name: codehunt
description: "A new Flutter project."
 
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6 
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1
  get: ^4.6.6
  firebase_app_check: ^0.3.0+1
  firebase_core: ^3.1.0
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  cloud_firestore: ^5.0.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  buttons_tabbar: ^1.3.10
  flutter_facebook_auth: ^7.0.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  font_awesome_icon_class: ^0.0.6

  flutter_lints: ^3.0.0
 
 
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/

    - assets/icons/
    

 
  fonts:
    - family: English
      fonts:

        - asset: assets/fonts/Lora-Regular.ttf
          style: italic
          weight: 700
 
